# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

  adapter: postgresql
  encoding: unicode
  database: pokemonAPI_development
  pool: 1
  username: rakhi
  password: 123456


test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: pokemonAPI_test
  pool: 1
  username: rakhi
  password: 123456


production:
  <<: *default
  database: pokemonAPI_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
